apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whoami
  namespace: traefik-whoami
spec:
  parentRefs:
    - name: lab
      namespace: traefik
  hostnames:
    - demo.lab.local
  rules:
    - backendRefs:
        - name: whoami
          port: 80